name: seal
dependencies:
  - fescudie::anacore=2.10.0
  - conda-forge::email_validator=1.3.0
  - conda-forge::flask=2.2.2
  - conda-forge::flask-admin=1.6.0
  - conda-forge::flask-apscheduler=1.12.4
  - conda-forge::flask-bcrypt=1.0.1
  - conda-forge::flask-login=0.6.2
  - conda-forge::flask-migrate=4.0.1
  - conda-forge::flask-restful=0.3.9
  - conda-forge::flask-sqlalchemy=2.5.1
  - conda-forge::flask-testing=0.8.1
  - conda-forge::flask-wtf=1.0.1
  - conda-forge::pandas=1.1.5
  - conda-forge::pillow=8.2.0
  - conda-forge::postgresql=14.5
  - conda-forge::psycopg2=2.9.3
  - conda-forge::pytest=7.2.0
  - conda-forge::python=3.7.12
  - conda-forge::tzlocal=4.2
  - bioconda::ensembl-vep=104.3
