FLASK:
  ENV: 'development' # choice : 'development', 'stage', 'production'
  SECRET_KEY: 'your_secret_key' # create your app secret key
  SQLALCHEMY_DATABASE_URI: 'postgresql:///seal' # you can edit the database configuration
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SCHEDULER_API_ENABLED: true
  SCHEDULER_TIMEZONE: 'Europe/Paris'
  SCHEDULER_JOB_DEFAULTS:
    coalesce: false
    max_instances: 1
  MAINTENANCE: false # Set to true or false
  FLASK_ADMIN_SWATCH: 'darkly'
  SESSION_COOKIE_NAME: "seal38"
GENOME: "grch38" # choices : "grch37", "grch38"
